backend:
  name: github
  repo: Shawn-D-souza/abcdritz7-93143bd6
  branch: main


media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"

publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    sortable_fields: ["title", "date", "author", "description", "updated_date"]
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL Slug", name: "slug", widget: "string", hint: "Example: my-awesome-post (No spaces!)" }
      - { label: "Category", name: "category", widget: "relation", collection: "categories", search_fields: ["title"], value_field: "title", display_fields: ["title"], default: "Technology" }
      - { label: "Author", name: "author", widget: "string", default: "Admin" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Last Updated", name: "updated_date", widget: "datetime", required: true }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false }
      - { label: "Thumbnail Alt Text", name: "thumbnail_alt", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Custom Head Script", name: "custom_head", widget: "text", required: false, hint: "Paste your custom script tags, JSON-LD, or analytics code here." }
      - { label: "Body", name: "body", widget: "markdown", editor_components: ["youtube", "custom-table", "faq", "image", "code-block"] }

  - name: "categories"
    label: "Categories"
    folder: "src/content/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }

editor:
  preview: false
